const colleges2024 = [
    { name: "طب المنصورة", minScore: 304.39, percent: 95.12, type: "علوم", faculty: "الطب" },
    { name: "هندسة بترول وتعدين السويس", minScore: 304.39, percent: 95.12, type: "رياضة", faculty: "الهندسة" },
    { name: "طب دمياط", minScore: 303.90, percent: 95.00, type: "علوم", faculty: "الطب" },
    { name: "طب الزقازيق", minScore: 303.90, percent: 95.00, type: "علوم", faculty: "الطب" },
    { name: "طب الإسكندرية", minScore: 303.41, percent: 94.88, type: "علوم", faculty: "الطب" },
    { name: "طب سوهاج", minScore: 303.41, percent: 94.88, type: "علوم", faculty: "الطب" },
    { name: "طب فاقوس", minScore: 303.41, percent: 94.88, type: "علوم", faculty: "الطب" },
    { name: "طب القاهرة", minScore: 302.44, percent: 94.64, type: "علوم", faculty: "الطب" },
    { name: "طب طنطا", minScore: 302.44, percent: 94.64, type: "علوم", faculty: "الطب" },
    { name: "طب كفر الشيخ", minScore: 301.95, percent: 94.52, type: "علوم", faculty: "الطب" },
    { name: "طب بنها", minScore: 301.46, percent: 94.40, type: "علوم", faculty: "الطب" },
    { name: "طب بور سعيد", minScore: 301.46, percent: 94.40, type: "علوم", faculty: "الطب" },
    { name: "طب عين شمس", minScore: 300.98, percent: 94.28, type: "علوم", faculty: "الطب" },
    { name: "طب أسنان المنصورة", minScore: 300.98, percent: 94.28, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب المنوفية بشبين الكوم", minScore: 300.98, percent: 94.28, type: "علوم", faculty: "الطب" },
    { name DARK_OLIVE_GREEN: "طب قناة السويس بالإسماعيلية", minScore: 300.49, percent: 94.16, type: "علوم", faculty: "الطب" },
    { name: "طب حلوان", minScore: 300.49, percent: 94.16, type: "علوم", faculty: "الطب" },
    { name: "طب أسيوط", minScore: 300.00, percent: 94.04, type: "علوم", faculty: "الطب" },
    { name: "طب الفيوم", minScore: 299.51, percent: 93.91, type: "علوم", faculty: "الطب" },
    { name: "طب السويس", minScore: 299.51, percent: 93.91, type: "علوم", faculty: "الطب" },
    { name: "طب المنيا", minScore: 299.02, percent: 93.79, type: "علوم", faculty: "الطب" },
    { name: "طب بني سويف", minScore: 299.02, percent: 93.79, type: "علوم", faculty: "الطب" },
    { name: "طب جنوب الوادي", minScore: 299.02, percent: 93.79, type: "علوم", faculty: "الطب" },
    { name: "طب أسنان جنوب الوادي", minScore: 299.02, percent: 93.79, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب الأقصر", minScore: 298.54, percent: 93.67, type: "علوم", faculty: "الطب" },
    { name: "طب العريش", minScore: 298.54, percent: 93.67, type: "علوم", faculty: "الطب" },
    { name: "طب أسوان", minScore: 298.05, percent: 93.55, type: "علوم", faculty: "الطب" },
    { name: "طب الوادي الجديد", minScore: 298.05, percent: 93.55, type: "علوم", faculty: "الطب" },
    { name: "طب أسنان طنطا", minScore: 297.56, percent: 93.43, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان كفر الشيخ", minScore: 297.56, percent: 93.43, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان أسيوط", minScore: 297.56, percent: 93.43, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان الزقازيق", minScore: 297.56, percent: 93.43, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان المنيا", minScore: 297.56, percent: 93.43, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان المنوفية", minScore: 297.07, percent: 93.31, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان قناة السويس بالإسماعيلية", minScore: 297.07, percent: 93.31, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان عين شمس", minScore: 297.07, percent: 93.31, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان الإسكندرية", minScore: 297.07, percent: 93.31, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان القاهرة", minScore: 297.07, percent: 93.31, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان السويس", minScore: 296.59, percent: 93.19, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان الفيوم", minScore: 296.59, percent: 93.19, type: "علوم", faculty: "طب الأسنان" },
    { name: "طب أسنان بني سويف", minScore: 296.59, percent: 93.19, type: "علوم", faculty: "طب الأسنان" },
    { name: "صيدلة سوهاج", minScore: 296.10, percent: 93.07, type: "علوم", faculty: "الصيدلة" },
    { name: "علاج طبيعي كفر الشيخ", minScore: 295.61, percent: 92.94, type: "علوم", faculty: "العلاج الطبيعي" },
    { name: "علاج طبيعي بورسعيد", minScore: 295.12, percent: 92.82, type: "علوم", faculty: "العلاج الطبيعي" },
    { name: "علاج طبيعي بنها", minScore: 295.12, percent: 92.82, type: "علوم", faculty: "العلاج الطبيعي" },
    { name: "علاج طبيعي جنوب الوادي", minScore: 295.12, percent: 92.82, type: "علوم", faculty: "العلاج الطبيعي" },
    { name: "صيدلة المنصورة", minScore: 294.63, percent: 92.70, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة جنوب الوادي", minScore: 294.63, percent: 92.70, type: "علوم", faculty: "الصيدلة" },
    { name: "علاج طبيعي قناة السويس", minScore: 294.63, percent: 92.70, type: "علوم", faculty: "العلاج الطبيعي" },
    { name: "علاج طبيعي القاهرة", minScore: 294.63, percent: 92.70, type: "علوم", faculty: "العلاج الطبيعي" },
    { name: "علاج طبيعي بني سويف", minScore: 294.15, percent: 92.58, type: "علوم", faculty: "العلاج الطبيعي" },
    { name: "صيدلة أسيوط", minScore: 294.15, percent: 92.58, type: "علوم", faculty: "الصيدلة" },
    { name: "علاج طبيعي السويس", minScore: 294.15, percent: 92.58, type: "علوم", faculty: "العلاج الطبيعي" },
    { name: "صيدلة طنطا", minScore: 293.66, percent: 92.46, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة الزقازيق", minScore: 293.66, percent: 92.46, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة وتصنيع دوائي كفر الشيخ", minScore: 293.66, percent: 92.46, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة المنيا", minScore: 293.66, percent: 92.46, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة بني سويف", minScore: 293.17, percent: 92.33, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة قناة السويس بالإسماعيلية", minScore: 293.17, percent: 92.33, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة الإسكندرية", minScore: 293.17, percent: 92.33, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة بور سعيد", minScore: 293.17, percent: 92.33, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة القاهرة", minScore: 293.17, percent: 92.33, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة دمنهور", minScore: 293.17, percent: 92.33, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة المنوفية", minScore: 293.17, percent: 92.33, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة عين شمس", minScore: 292.68, percent: 92.21, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة الفيوم", minScore: 292.68, percent: 92.21, type: "علوم", faculty: "الصيدلة" },
    { name: "هندسة القاهرة", minScore: 292.68, percent: 92.21, type: "رياضة", faculty: "الهندسة" },
    { name: "هندسة إلكترونية المنوفية بمنوف", minScore: 292.68, percent: 92.21, type: "رياضة", faculty: "الهندسة" },
    { name: "صيدلة مدينة السادات", minScore: 292.20, percent: 92.09, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة حلوان", minScore: 292.20, percent: 92.09, type: "علوم", faculty: "الصيدلة" },
    { name: "صيدلة الوادي الجديد", minScore: 292.20, percent: 92.09, type: "علوم", faculty: "الصيدلة" },
    { name: "حاسبات ومعلومات سوهاج علوم", minScore: 290.24, percent: 91.58, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "هندسة المنصورة", minScore: 289.27, percent: 91.33, type: "رياضة", faculty: "الهندسة" },
    { name: "هندسة عين شمس", minScore: 288.78, percent: 91.21, type: "رياضة", faculty: "الهندسة" },
    { name: "حاسبات ومعلومات قنا علوم", minScore: 288.78, percent: 91.21, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "هندسة سوهاج", minScore: 288.29, percent: 91.09, type: "رياضة", faculty: "الهندسة" },
    { name: "هندسة قناة السويس بالإسماعيلية", minScore: 287.80, percent: 90.97, type: "رياضة", faculty: "الهندسة" },
    { name: "هندسة الزقازيق", minScore: 287.32, percent: 90.85, type: "رياضة", faculty: "الهندسة" },
    { name: "طب بيطري سوهاج", minScore: 287.32, percent: 90.85, type: "علوم", faculty: "الطب البيطري" },
    { name: "حاسبات ومعلومات أسيوط علوم", minScore: 287.32, percent: 90.85, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "حاسبات ومعلومات المنيا علوم", min update: 286.83, percent: 90.73, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "علوم البترول والتعدين مطروح", minScore: 286.83, percent: 90.73, type: "علوم", faculty: "علوم" },
    { name: "طب بيطري المنصورة", minScore: 286.83, percent: 90.73, type: "علوم", faculty: "الطب البيطري" },
    { name: "حاسبات ومعلومات الأقصر علوم", minScore: 286.34, percent: 90.61, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "هندسة دمياط", minScore: 286.34, percent: 90.61, type: "رياضة", faculty: "الهندسة" },
    { name: "حاسبات ومعلومات المنصورة علوم", minScore: 285.85, percent: 90.49, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "حاسبات ومعلومات دمياط علوم", minScore: 285.37, percent: 90.37, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "هندسة طنطا", minScore: 285.37, percent: 90.37, type: "رياضة", faculty: "الهندسة" },
    { name: "هندسة بور سعيد", minScore: 284.88, percent: 90.24, type: "رياضة", faculty: "الهندسة" },
    { name: "حاسبات ومعلومات الزقازيق علوم", minScore: 284.88, percent: 90.24, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "طب بيطري جنوب الوادي", minScore: 284.39, percent: 90.12, type: "علوم", faculty: "الطب البيطري" },
    { name: "هندسة بنها بشبرا", minScore: 284.39, percent: 90.12, type: "رياضة", faculty: "الهندسة" },
    { name: "حاسبات ومعلومات بني سويف علوم", minScore: 284.39, percent: 90.12, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "هندسة الإسكندرية", minScore: 284.39, percent: 90.12, type: "رياضة", faculty: "الهندسة" },
    { name: "طب بيطري الزقازيق", minScore: 283.90, percent: 90.00, type: "علوم", faculty: "الطب البيطري" },
    { name: "حاسبات وذكاء اصطناعي القاهرة علوم", minScore: 283.90, percent: 90.00, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "طب بيطري كفر الشيخ", minScore: 283.90, percent: 90.00, type: "علوم", faculty: "الطب البيطري" },
    { name: "هندسة بنها", minScore: 283.41, percent: 89.88, type: "رياضة", faculty: "الهندسة" },
    { name: "هندسة كفر الشيخ", minScore: 283.41, percent: 89.88, type: "رياضة", faculty: "الهندسة" },
    { name: "حاسبات ومعلومات طنطا علوم", minScore: 283.41, percent: 89.88, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "حاسبات ومعلومات دمنهور بالنوبارية علوم", minScore: 283.41, percent: 89.88, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "هندسة دمنهور", minScore: 282.93, percent: 89.76, type: "رياضة", faculty: "الهندسة" },
    { name: "هندسة حلوان", minScore: 282.93, percent: 89.76, type: "رياضة", faculty: "الهندسة" },
    { name: "حاسبات ومعلومات عين شمس علوم", minScore: 282.93, percent: 89.76, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "حاسبات ومعلومات قناة السويس بالإسماعيلية علوم", minScore: 282.93, percent: 89.76, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "طب بيطري أسيوط", minScore: 282.93, percent: 89.76, type: "علوم", faculty: "الطب البيطري" },
    { name: "هندسة السويس", minScore: 282.44, percent: 89.64, type: "رياضة", faculty: "الهندسة" },
    { name: "هندسة المنوفية بشبين الكوم", minScore: 282.44, percent: 89.64, type: "رياضة", faculty: "الهندسة" },
    { name: "الذكاء الاصطناعي كفر الشيخ علوم", minScore: 282.44, percent: 89.64, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "حاسبات وذكاء اصطناعي جنوب الوادي فرع الغردقة علوم", minScore: 282.44, percent: 89.64, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "هندسة حلوان بالمطرية", minScore: 281.95, percent: 89.52, type: "رياضة", faculty: "الهندسة" },
    { name: "حاسبات ومعلومات كفر الشيخ علوم", minScore: 281.95, percent: 89.52, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "هندسة جنوب الوادي", minScore: 281.95, percent: 89.52, type: "رياضة", faculty: "الهندسة" },
    { name: "حاسبات وعلوم البيانات الإسكندرية علوم", minScore: 281.46, percent: 89.39, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "حاسبات وذكاء اصطناعي بنها علوم", minScore: 281.46, percent: 89.39, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "هندسة الفيوم", minScore: 280.98, percent: 89.27, type: "رياضة", faculty: "الهندسة" },
    { name: "طب بيطري عين شمس", minScore: 280.98, percent: 89.27, type: "علوم", faculty: "الطب البيطري" },
    { name: "حاسبات وذكاء اصطناعي حلوان علوم", minScore: 280.98, percent: 89.27, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "طب بيطري المنيا", minScore: 280.49, percent: 89.15, type: "علوم", faculty: "الطب البيطري" },
    { name: "طب بيطري المنوفية", minScore: 280.49, percent: 89.15, type: "علوم", faculty: "الطب البيطري" },
    { name: "هندسة بني سويف", minScore: 280.00, percent: 89.03, type: "رياضة", faculty: "الهندسة" },
    { name: "حاسبات ومعلومات السويس علوم", minScore: 280.00, percent: 89.03, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "حاسبات ومعلومات العريش علوم", minScore: 280.00, percent: 89.03, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "حاسبات ومعلومات المنوفية بشبين الكوم علوم", minScore: 279.51, percent: 88.91, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "هندسة أسوان", minScore: 279.51, percent: 88.91, type: "رياضة", faculty: "الهندسة" },
    { name: "هندسة المنيا", minScore: 279.51, percent: 88.91, type: "رياضة", faculty: "الهندسة" },
    { name: "هندسة أسيوط", minScore: 279.51, percent: 88.91, type: "رياضة", faculty: "الهندسة" },
    { name: "طب بيطري دمنهور", minScore: 279.51, percent: 88.91, type: "علوم", faculty: "الطب البيطري" },
    { name "طب بيطري الإسكندرية", minScore: 279.51, percent: 88.91, type: "علوم", faculty: "الطب البيطري" },
    { name: "حاسبات ومعلومات الفيوم علوم", minScore: 279.02, percent: 88.79, type: "علوم", faculty: "حاسبات ومعلومات" },
    { name: "هندسة الطاقة أسوان", minScore: 279.02, percent: 88.79, type: "رياضة", faculty: "الهندسة" },
    // كليات العلوم
    { name: "علوم المنصورة", minScore: 278.54, percent: 88.67, type: "علوم", faculty: "علوم" },
    { name: "علوم القاهرة", minScore: 278.05, percent: 88.55, type: "علوم", faculty: "علوم" },
    { name: "علوم عين شمس", minScore: 277.56, percent: 88.43, type: "علوم", faculty: "علوم" },
    { name: "علوم الإسكندرية", minScore: 277.07, percent: 88.31, type: "علوم", faculty: "علوم" },
    { name: "علوم طنطا", minScore: 276.59, percent: 88.19, type: "علوم", faculty: "علوم" },
    { name: "علوم الزقازيق", minScore: 276.10, percent: 88.07, type: "علوم", faculty: "علوم" },
    { name: "علوم بني سويف", minScore: 275.61, percent: 87.94, type: "علوم", faculty: "علوم" },
    { name: "علوم أسيوط", minScore: 275.12, percent: 87.82, type: "علوم", faculty: "علوم" },
    { name: "علوم الفيوم", minScore: 274.63, percent: 87.70, type: "علوم", faculty: "علوم" },
    { name: "علوم سوهاج", minScore: 274.15, percent: 87.58, type: "علوم", faculty: "علوم" },
    // كليات الزراعة
    { name: "زراعة القاهرة", minScore: 273.66, percent: 87.46, type: "علوم", faculty: "الزراعة" },
    { name: "زراعة عين شمس", minScore: 273.17, percent: 87.33, type: "علوم", faculty: "الزراعة" },
    { name: "زراعة المنصورة", minScore: 272.68, percent: 87.21, type: "علوم", faculty: "الزراعة" },
    { name: "زراعة الإسكندرية", minScore: 272.20, percent: 87.09, type: "علوم", faculty: "الزراعة" },
    { name: "زراعة أسيوط", minScore: 271.71, percent: 86.97, type: "علوم", faculty: "الزراعة" },
    { name: "زراعة بني سويف", minScore: 271.22, percent: 86.85, type: "علوم", faculty: "الزراعة" },
    { name: "زراعة المنيا", minScore: 270.73, percent: 86.73, type: "علوم", faculty: "الزراعة" },
    { name: "زراعة سوهاج", minScore: 270.24, percent: 86.61, type: "علوم", faculty: "الزراعة" },
    // كليات التجارة
    { name: "تجارة القاهرة", minScore: 269.76, percent: 86.49, type: "أدبي", faculty: "التجارة" },
    { name: "تجارة عين شمس", minScore: 269.27, percent: 86.37, type: "أدبي", faculty: "التجارة" },
    { name: "تجارة الإسكندرية", minScore: 268.78, percent: 86.24, type: "أدبي", faculty: "التجارة" },
    { name: "تجارة المنصورة", minScore: 268.29, percent: 86.12, type: "أدبي", faculty: "التجارة" },
    { name: "تجارة طنطا", minScore: 267.80, percent: 86.00, type: "أدبي", faculty: "التجارة" },
    { name: "تجارة الزقازيق", minScore: 267.32, percent: 85.88, type: "أدبي", faculty: "التجارة" },
    { name: "تجارة بني سويف", minScore: 266.83, percent: 85.76, type: "أدبي", faculty: "التجارة" },
    { name: "تجارة أسيوط", minScore: 266.34, percent: 85.64, type: "أدبي", faculty: "التجارة" },
    { name: "تجارة سوهاج", minScore: 265.85, percent: 85.52, type: "أدبي", faculty: "التجارة" },
    // كليات التربية
    { name: "تربية القاهرة", minScore: 265.37, percent: 85.39, type: "أدبي", faculty: "التربية" },
    { name: "تربية عين شمس", minScore: 264.88, percent: 85.27, type: "أدبي", faculty: "التربية" },
    { name: "تربية الإسكندرية", minScore: 264.39, percent: 85.15, type: "أدبي", faculty: "التربية" },
    { name: "تربية المنصورة", minScore: 263.90, percent: 85.03, type: "أدبي", faculty: "التربية" },
    { name: "تربية طنطا", minScore: 263.41, percent: 84.91, type: "أدبي", faculty: "التربية" },
    { name: "تربية الزقازيق", minScore: 262.93, percent: 84.79, type: "أدبي", faculty: "التربية" },
    { name: "تربية بني سويف", minScore: 262.44, percent: 84.67, type: "أدبي", faculty: "التربية" },
    { name: "تربية أسيوط", minScore: 261.95, percent: 84.55, type: "أدبي", faculty: "التربية" },
    // كليات الآداب
    { name: "آداب القاهرة", minScore: 261.46, percent: 84.43, type: "أدبي", faculty: "الآداب" },
    { name: "آداب عين شمس", minScore: 260.98, percent: 84.31, type: "أدبي", faculty: "الآداب" },
    { name: "آداب الإسكندرية", minScore: 260.49, percent: 84.19, type: "أدبي", faculty: "الآداب" },
    { name: "آداب المنصورة", minScore: 260.00, percent: 84.06, type: "أدبي", faculty: "الآداب" },
    { name: "آداب طنطا", minScore: 259.51, percent: 83.94, type: "أدبي", faculty: "الآداب" },
    { name: "آداب الزقازيق", minScore: 259.02, percent: 83.82, type: "أدبي", faculty: "الآداب" },
    { name: "آداب بني سويف", minScore: 258.54, percent: 83.70, type: "أدبي", faculty: "الآداب" },
    { name: "آداب أسيوط", minScore: 258.05, percent: 83.58, type: "أدبي", faculty: "الآداب" },
    // كليات الحقوق
    { name: "حقوق القاهرة", minScore: 257.56, percent: 83.46, type: "أدبي", faculty: "الحقوق" },
    { name: "حقوق عين شمس", minScore: 257.07, percent: 83.33, type: "أدبي", faculty: "الحقوق" },
    { name: "حقوق الإسكندرية", minScore: 256.59, percent: 83.21, type: "أدبي", faculty: "الحقوق" },
    { name: "حقوق المنصورة", minScore: 256.10, percent: 83.09, type: "أدبي", faculty: "الحقوق" },
    { name: "حقوق بني سويف", minScore: 255.61, percent: 82.97, type: "أدبي", faculty: "الحقوق" },
    // كليات السياحة والفنادق
    { name: "سياحة وفنادق الإسكندرية", minScore: 255.12, percent: 82.85, type: "أدبي", faculty: "السياحة والفنادق" },
    { name: "سياحة وفنادق الفيوم", minScore: 254.63, percent: 82.73, type: "أدبي", faculty: "السياحة والفنادق" },
    // كليات التمريض
    { name: "تمريض القاهرة", minScore: 254.15, percent: 82.61, type: "علوم", faculty: "التمريض" },
    { name: "تمريض عين شمس", minScore: 253.66, percent: 82.49, type: "علوم", faculty: "التمريض" },
    { name: "تمريض الإسكندرية", minScore: 253.17, percent: 82.37, type: "علوم", faculty: "التمريض" },
    { name: "تمريض المنصورة", minScore: 252.68, percent: 82.24, type: "علوم", faculty: "التمريض" },
    // كليات التربية الرياضية
    { name: "تربية رياضية القاهرة", minScore: 252.20, percent: 82.12, type: "أدبي", faculty: "التربية الرياضية" },
    { name: "تربية رياضية الإسكندرية", minScore: 251.71, percent: 82.00, type: "أدبي", faculty: "التربية الرياضية" },
    // كليات الخدمة الاجتماعية
    { name: "خدمة اجتماعية الفيوم", minScore: 251.22, percent: 81.88, type: "أدبي", faculty: "الخدمة الاجتماعية" },
    { name: "خدمة اجتماعية أسيوط", minScore: 250.73, percent: 81.76, type: "أدبي", faculty: "الخدمة الاجتماعية" }
];
